### ISSUE TITLE
xfce环境报错

### ISSUE THREAD

**Issue by shootheart** [Pylogmon/earth_wallpaper#35]
版本：2.2.1
python：3.10.9

执行xfce.py时报错

```python
Traceback (most recent call last):
  File "/opt/earth-wallpaper-bin/earth_wallpaper/thread.py", line 35, in run
    set_wallpaper(x.download_path)
  File "/opt/earth-wallpaper-bin/earth_wallpaper/utils/setWallpaper.py", line 62, in set_wallpaper
    x.run()
  File "/opt/earth-wallpaper-bin/earth_wallpaper/utils/systems/linux/xfce.py", line 11, in run
    output = output.splitlines()
  File "/usr/lib/python3.10/os.py", line 1017, in __getattr__
    return getattr(self._stream, name)
AttributeError: '_io.TextIOWrapper' object has no attribute 'splitlines'
```

**Comment by Pylogmon** [comment]
麻烦测试一下最新自动构建版本是否存在问题 
[download](https://github.com/Pylogmon/earth_wallpaper/actions/runs/4250471230)

**Comment by shootheart** [comment]
> 麻烦测试一下最新自动构建版本是否存在问题 [download](https://github.com/Pylogmon/earth_wallpaper/actions/runs/4250471230)

可以了，没有问题

**Comment by Pylogmon** [comment]
好的，感谢反馈👍
